### ISSUE TITLE
PublicSuffixListManager writes empty cache if http request fails

### ISSUE THREAD

**Issue by mikegreiling** [jeremykendall/php-domain-parser#119]
When for whatever reason the list manager cannot pull the contents of `publicsuffix.org`, it will cache an empty suffix list.  I'm guessing this is undesirable behavior in most use cases and it would probably be better to have it not write to the cache at all (overwriting a useful, if not up-to-date cache with a useless one).

I think the fix would be pretty simple.  Just add `if (empty($data)) return false;` to `PublicSuffixListManager::write()`, and update `refreshPublicSuffixList()` to abort if `fetchListFromSource()` returns false.

**Comment by jeremykendall** [comment]
Great catch! Any chance you'd be willing to put a PR together?

**Comment by nyamsprod** [comment]
This issue has been resolve in the new major release as caching is now done using any [PSR-16 cache](http://www.php-fig.org/psr/psr-16/) implementation.
