### ISSUE TITLE
Call to undefined method Pdp\Uri\Url::getHost() 

### ISSUE THREAD

**Issue by flipside555** [jeremykendall/php-domain-parser#120]
Hi,

I'm trying to set this up according to the examples. I'm getting an error calling getHost(). No doubt something simple. I'd appreciate any help.
```
<?php
require_once __DIR__ . '/vendor/autoload.php';
use Pdp\PublicSuffixListManager;
use Pdp\Parser;
$pslManager = new PublicSuffixListManager();
$parser = new Parser($pslManager->getList());
$host = 'http://user:pass@www.pref.okinawa.jp:8080/path/to/page.html?query=string#fragment';
$url = $parser->parseUrl($host);
var_dump($url);
$host = $url->getHost();
```

php parsetemp.php
object(Pdp\Uri\Url)#6 (8) {
  ["scheme":"Pdp\Uri\Url":private]=>
  string(4) "http"
  ["host":"Pdp\Uri\Url":private]=>
  object(Pdp\Uri\Url\Host)#5 (4) {
    ["subdomain":"Pdp\Uri\Url\Host":private]=>
    string(3) "www"
    ["registerableDomain":"Pdp\Uri\Url\Host":private]=>
    string(15) "pref.okinawa.jp"
    ["publicSuffix":"Pdp\Uri\Url\Host":private]=>
    string(10) "okinawa.jp"
    ["host":"Pdp\Uri\Url\Host":private]=>
    string(19) "www.pref.okinawa.jp"
  }
  ["port":"Pdp\Uri\Url":private]=>
  string(4) "8080"
  ["user":"Pdp\Uri\Url":private]=>
  string(4) "user"
  ["pass":"Pdp\Uri\Url":private]=>
  string(4) "pass"
  ["path":"Pdp\Uri\Url":private]=>
  string(18) "/path/to/page.html"
  ["query":"Pdp\Uri\Url":private]=>
  string(12) "query=string"
  ["fragment":"Pdp\Uri\Url":private]=>
  string(8) "fragment"
}
PHP Fatal error:  Call to undefined method Pdp\Uri\Url::getHost() in /root/scripts/parsetemp.php on line 12

**Comment by jeremykendall** [comment]
You're probably not using the latest dev version. That's a new feature that
hasn't made it to a stable release yet.

On Tuesday, March 15, 2016, flipside555 <notifications@github.com> wrote:

> Hi,
>
> I'm trying to set this up according to the examples. I'm getting an error
> calling getHost(). No doubt something simple. I'd appreciate any help.
>
> <?php
> require_once __DIR__ . '/vendor/autoload.php';
> use Pdp\PublicSuffixListManager;
> use Pdp\Parser;
> $pslManager = new PublicSuffixListManager();
> $parser = new Parser($pslManager->getList());
> $host = 'http://user:pass@www.pref.okinawa.jp:8080/path/to/page.html?query=string#fragment';
> $url = $parser->parseUrl($host);
> var_dump($url);
> $host = $url->getHost();
>
> php parsetemp.php
> object(Pdp\Uri\Url)#6
> <https://github.com/jeremykendall/php-domain-parser/issues/6> (8) {
> ["scheme":"Pdp\Uri\Url":private]=>
> string(4) "http"
> ["host":"Pdp\Uri\Url":private]=>
> object(Pdp\Uri\Url\Host)#5
> <https://github.com/jeremykendall/php-domain-parser/issues/5> (4) {
> ["subdomain":"Pdp\Uri\Url\Host":private]=>
> string(3) "www"
> ["registerableDomain":"Pdp\Uri\Url\Host":private]=>
> string(15) "pref.okinawa.jp"
> ["publicSuffix":"Pdp\Uri\Url\Host":private]=>
> string(10) "okinawa.jp"
> ["host":"Pdp\Uri\Url\Host":private]=>
> string(19) "www.pref.okinawa.jp"
> }
> ["port":"Pdp\Uri\Url":private]=>
> string(4) "8080"
> ["user":"Pdp\Uri\Url":private]=>
> string(4) "user"
> ["pass":"Pdp\Uri\Url":private]=>
> string(4) "pass"
> ["path":"Pdp\Uri\Url":private]=>
> string(18) "/path/to/page.html"
> ["query":"Pdp\Uri\Url":private]=>
> string(12) "query=string"
> ["fragment":"Pdp\Uri\Url":private]=>
> string(8) "fragment"
> }
> PHP Fatal error: Call to undefined method Pdp\Uri\Url::getHost() in
> /root/scripts/parsetemp.php on line 12
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jeremykendall/php-domain-parser/issues/120
>


-- 
Sent from Gmail Mobile

**Comment by flipside555** [comment]
Ok. That'll be it. Thanks.

**Comment by flipside555** [comment]
So, is there a way to install the latest development version using Composer?

**Comment by jeremykendall** [comment]
Sure! Just add dev-master as the version.

On Tuesday, March 15, 2016, flipside555 <notifications@github.com> wrote:

> So, is there a way to install the latest development version using
> Composer?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/jeremykendall/php-domain-parser/issues/120#issuecomment-196817047
>


-- 
Sent from Gmail Mobile

**Comment by flipside555** [comment]
Got it. Thanks.
