### ISSUE TITLE
[Feature request] Distinguish ICANN from private domain

### ISSUE THREAD

**Issue by nyamsprod** [jeremykendall/php-domain-parser#179]
A recent post on [reddit](https://www.reddit.com/r/PHP/comments/52www5/tldextract_library_for_extraction_of_domain_parts/d7oyhe3) highlighted that the current library can not distinguish beetwen ICANN and Private Domains, although the PDL contains two distinctive sections to highlight the difference. 

Is it possible to add this missing feature to the current library ? I understand handling this would mean changing the current parser and the generated data. It may even mean a Backward compatible break ? What do you think ?

**Comment by jeremykendall** [comment]
Closing in favor of keeping all updates/info in PR #180.
