### ISSUE TITLE
v4.0

### ISSUE THREAD

**Issue by huglester** [jeremykendall/php-domain-parser#181]
Hello

I wonder if there is going v4 be released someday? 
I am not pushing anyone, just asking!

thanks

**Comment by jeremykendall** [comment]
Maybe? There will definitely be additional releases. What would you like to see in a new version that's not available now?

I've been so busy with work and two kiddos that I haven't had time to give this library the attention it deserves. As soon as things calm down I'll definitely get back to maintenance, feature requests, new versions, etc. There are some really great [pull requests](https://github.com/jeremykendall/php-domain-parser/pulls) from @mikegreiling, @oxigenka, and @nyamsprod that can give you an idea of features/updates that will be added as soon as I can get back to them.

**Comment by jeremykendall** [comment]
(I'm going to close this, but please feel free to reopen for any additional questions or comments you'd like to add.)

**Comment by nyamsprod** [comment]
@jeremykendall If v4 is still a thing I'd like you to consider this idea I had about the package I believe It would even solve many current issues. This is just a proposal feel free to reject everything if you don't like it 👍 

The main "issue generator" is the PublicSuffixListManager class which have too many responsabilities:

- It downloads the data from mozilla
- It caches the downloaded data 
- It parses the downloaded data
- it returns the data to be consumed by other parts of the library

This gives the class too many responsabilites and explain many of the current bug found. I would suggest rewritten this class is this manner

```php
<?php

use Pdp\HttpAdapter\HttpAdapterInterface;
use Pdp\PublicSuffixList\ParserInterface;
use Psr\SimpleCache\CacheInterface;

public function PublicSuffixListManager::__construct(
        ParserInterface $parser = null,
        HttpAdapterInterface $client = null,
        CacheInterface $cache = null,
);
```

This way:

- SRP is enforced on the PublicSuffixListManager and it would be only responsible for returning the data to be consumed by other parts of the library.
- The cache is done using [PSR-16](http://www.php-fig.org/psr/psr-16/) so to resolve all current caching issues and also enable better caching solution.
- The PDP parser is also made into a interface to enable switching it too if needed.

last but not least I would consider bumping PHP requirements to either PHP5.6 or PHP7 👍 

What do you think ?

**Comment by jeremykendall** [comment]
I love everything about that idea. Want to open an issue with the necessary tasks in a list of checkboxes?
