### ISSUE TITLE
Breaks when trying to parse 'file:///path1/path2'

### ISSUE THREAD

**Issue by orottier** [jeremykendall/php-domain-parser#183]
```PHP error:  Undefined index: host in Pdp/Parser.php on line 98```

It's the three slashes that matter here, it returns a null host correctly when using two slashes. Also, this only happens on `file:///` schemes, `http:///` with three forward slashes work.

Also tested in `develop`@45c89d2, breaks too

**Comment by jeremykendall** [comment]
I'm not sure I understand your use case. php-domain-parser is intended to parse domains into their component parts using the Public Suffix List. This library is not intended for any other use, and definitely won't work with the `file` protocol. Why would you use it with `file`?

**Comment by orottier** [comment]
Thanks for replying! Surely I understand the scope of this repo, it's just that I rather not have my application crashing in case an unexpected input is entered. Feel free to close this issue and I'll write my own checks around it, or patch something along the lines (not tested)
``` 
       if ($parts === false || !isset($parts['host'])) {
            throw new SeriouslyMalformedUrlException($rawUrl);
       }
```

**Comment by jeremykendall** [comment]
Sorry for the delay in replying. You question/concern makes perfect sense now.

Unfortunately, I have zero time to immediately address your issue with a patch. Probably best for you to write your own check for the time being. I'll keep this issue open and add it to my To Do list.

**Comment by nyamsprod** [comment]
@orottier a new stable version of PHP Domain Parser has been released. This new version has remove any URL parsing capabilities from the package. If you are looking for a better parsert I'd suggest use one of the package listed on packagist https://packagist.org/?q=url rfc3986
