### ISSUE TITLE
Including Dependencies as a php package

### ISSUE THREAD

**Issue by xlplugins** [jeremykendall/php-domain-parser#190]
Hi, 

I have made a WordPress plugin using your domain parser.  Just before the launch, I realized that the dependencies PECL-INTL and PECL-IDN need to be installed. 

I cannot afford to put a notice to the users to install dependency first. Is there any 'way around' for this? 
Or any suggestions?

Thank You.

**Comment by jeremykendall** [comment]
Sorry for the late reply. intl and idn are both necessary to do what the parser does, so I'm afraid there's no way around that.
