### ISSUE TITLE
ext-curl should be a suggestion

### ISSUE THREAD

**Issue by christickner** [jeremykendall/php-domain-parser#191]
`ext-curl` is used by default to fetch the public suffix list. The public suffix list is only generated if the file is not included in the cache (the `data` dir by default). The git repository already contains these files as a warm cache. A user of this library, therefore, does not need to use `ext-curl` unless they are on a machine in which they want to refresh the cache. `ext-curl` should _not_ be a composer requirement, but rather it should be a suggestion.

1. Let's remove the composer dependency on `ext-curl` and use core PHP file functions by default
2. We have the working CurlHttpAdapter so we can keep it and default to it if `ext-curl` is installed on the machine

This way, apps that depend on this library won't need to install `ext-curl`. `ext-curl` will now be optional and will only be used if it's installed.

Are there any reasons why `ext-curl` was used, to begin with?

https://github.com/jeremykendall/php-domain-parser/blob/develop/src/Pdp/HttpAdapter/CurlHttpAdapter.php

`CURLOPT_RETURNTRANSFER` does nothing after 5.1.3 and we require `PHP >=5.3.0`

**Comment by nyamsprod** [comment]
@christickner a new version of PDP is about to be release and the `ext-curl` will be put in the suggestion part of the composer package. I should stress out that even if you don't have/need curl to use the library you should *definetly* use a mechanism to update the PSL cache you are using for domain name resolution. 

You can have a first glance at the new version on the following branch https://github.com/jeremykendall/php-domain-parser/tree/v5
