### ISSUE TITLE
New patch/minor release

### ISSUE THREAD

**Issue by nyamsprod** [jeremykendall/php-domain-parser#192]
Hi, any idea when a patch/minor release with all the bug fixes will be available on packagist. Last time I checked the last stable release date back in 2015 😥

**Comment by jeremykendall** [comment]
Ugh, it has been a while.

1. What about focusing on #187 and incorporating all of the ideas from existing issues and PRs?
1. What about dropping PHP 5 support entirely?

**Comment by nyamsprod** [comment]
If a new version is the next step then yeah dropping PHP5 is a no brainer IMHO. The only issue is do you targer PHP7 or PHP7.1 ?

While reviewing the issues and PRs I believe that most issues are around caching which should be solved by implementing PSR16 like suggested in #187. It would resolve 4 issues/PR (#119,  #78, #86, #178). 

The remaining issues/PR are about URI parsing but I have a completely different take on this. Your package is at its core a domain/host parser so I believe that URI parsing is out of scope and should be done elsewhere. I remember being suprised to see the `bin/parse` utility. Especially as I maintain a URI parser  I had someone complain to me that my application was parsing the URI differently on console and it took me sometimes to realize that my URI package was shipping your cli application too.

**Comment by jeremykendall** [comment]
> If a new version is the next step then yeah dropping PHP5 is a no brainer IMHO. The only issue is do you targer PHP7 or PHP7.1 ?

Yeah, a new version is the next step, I think. Based on everything I've learned since I've written this, I kind of feel like a rewrite is in order. Still thinking on that, but def leaning towards a re-write.

Based on the [supported versions](http://php.net/supported-versions.php) calendar, it seems like supporting PHP 7.0+ would be the way to go. It could even be argued that PHP 5.6 support is important as it's not yet EOL. Thoughts?

> While reviewing the issues and PRs I believe that most issues are around caching which should be solved by implementing PSR16 like suggested in #187. It would resolve 4 issues/PR (#119, #78, #86, #178).

👍 

> ... URI parsing is out of scope and should be done elsewhere.

Agree completely. The `parse` utility was intended as a sanity checker for domain parsing rather than a production tool for URI parsing. Probably should have either been better named or removed entirely.

**Comment by nyamsprod** [comment]
@jeremykendall I have mix feeling in still supporting PHP5.6 If we were one year ago I would have said why not. But right now, PHP7.2 is around the corner so still supporting PHP5.6 is like trying to accomodate two distinct ecosystems with one slowly but surely dying (look at HHVM decision for instance. So I would go with PHP7 which would maybe be also an incentive for our userbase to drop PHP5 too (One can always dream :) )

**Comment by jeremykendall** [comment]
OK, PHP 7.0+ it is. w00t!

Re-evalutating my understanding of the domain now. Looking at the current code I can see a lot of places for improvement.

**Comment by nyamsprod** [comment]
the new version developped here https://github.com/jeremykendall/php-domain-parser/tree/v5 will indeed required PHP7.0.0
