### ISSUE TITLE
Support for PHP 7.2 in 3.x branch

### ISSUE THREAD

**Issue by pamil** [jeremykendall/php-domain-parser#204]
Since `INTL_IDNA_VARIANT_2003` variant has been deprecated in PHP 7.2, using Payum which uses League/Uri which uses this library is impossible on that version (I've listed the details here: https://github.com/Sylius/Sylius/pull/8771#issuecomment-335422273).

The thing I'd like to introduce in `3.0.1` release is to change `idn_to_ascii` and `idn_to_utf8` function calls with something like:

Either:

```php
@idn_to_ascii($part)
```

Or:

```php
if (defined('INTL_IDNA_VARIANT_UTS46')) {
  $part = idn_to_ascii($part, 0, INTL_IDNA_VARIANT_UTS46);
} else {
  $part = idn_to_ascii($part);
}
```

Or:

```php
if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
  $part = @idn_to_ascii($part);
} else {
  $part = idn_to_ascii($part);
}
```

All I need to fix this is a branch based on `3.0.0` version tag available, the choice of the suitable solution, then merging a PR and releasing `3.0.1`. It really would help anyone using Payum with the most recent PHP version and I'll be grateful for help :)

**Comment by jeremykendall** [comment]
I don't see why we can't backport 7.2 support. @nyamsprod Thoughts?

**Comment by nyamsprod** [comment]
I could do it  but v4 code is really old 👎 I'll give it a try .. I need to look into it we will label this as a security patch :) also it means upping to v4 for domain parser too .

**Comment by jeremykendall** [comment]
Upping to v4? Adding that conditional will cause a BC break in php-domain-parser?

**Comment by pamil** [comment]
Looks like `thephpleague/uri` can use `4.0.3-alpha` without any other changes in the patch release so changes here are not really needed then :)

**Comment by pamil** [comment]
Not further needed since thephpleague/uri#105 was solved.
