### ISSUE TITLE
4.0 release

### ISSUE THREAD

**Issue by pamil** [jeremykendall/php-domain-parser#205]
Is there anything preventing 4.0 release? Could I be some help to make it happen?

**Comment by pamil** [comment]
It'd help a lot in bringing PHP 7.2 support for libraries depending on this one :)

**Comment by jeremykendall** [comment]
The only thing preventing it is a touch more refactoring and the fact that I haven't had any time at all to do the work. I've invited one of the community devs to become a core contributor. Hopefully they'll say yes and will be able to push us across the finish line.

**Comment by pamil** [comment]
Good to hear that! Keeping fingers crossed :)

**Comment by nyamsprod** [comment]
@pamil @jeremykendall so it was easier than I anticipated if you have time to review the code here https://github.com/bakame-php/php-domain-parser/tree/develop-v4 we can move forward and schedule a release. What's missing now is a CHANGELOG.md files to explain the differences between versions. But we will add one once we agree on everything else 👍

**Comment by jeremykendall** [comment]
@nyamsprod I trust you completely and I’m publicly and officially giving you the go ahead to merge and release on your own. When I finally have time and life calms down, we can get together and talk features and refactoring and such. Go for it!

**Comment by nyamsprod** [comment]
Version 5.0.0 is released get your copy using composer 👍 🥇

**Comment by pamil** [comment]
Thanks a lot! 🎉

**Comment by pamil** [comment]
@nyamsprod I've tried to upgrade League/Uri to the 5.0.0, but failed as it uses removed validation feature. It looks like a complicated dependency chain without a clean solution (as Payum requires old League/Uri version which uses old version of this library). Would you be willing to tag 4.0.3-alpha as 4.0.4 (without any support or maintenance promises)? It'd help us a lot!

**Comment by nyamsprod** [comment]
@pamil I'll do that when I have time. but I'd strongly suggest upgrading to League/uri 5.2 which has many bugfixes and enhancements in comparison to 5.0.0

**Comment by nyamsprod** [comment]
@pamil are you using php-domain-parser independently of league uri ? Because 5.2 no longer requires php-domain-parser and v5 of php-domain-parser is IMHO easier to use than v4 and last but not least both packages can be used separately (v5.2 and v5) so I would suggest doing that. Because even if I release v4.0.4 as stable it won't be resolve with v5.0.0 since it requires an older version (3.0.0) I know it's a mess

**Comment by pamil** [comment]
Here's our current dependency graph:

```
payum/payum    1.4.3      requires  league/uri (~4.0)

league/uri  4.2.2  requires  jeremykendall/php-domain-parser (^3.0)
OR
league/uri  4.2.3  requires  jeremykendall/php-domain-parser (4.0.3-alpha)
```

Since we're waiting for new Payum release which uses `league/uri:^5.0`, I'd like to support PHP 7.2 in Sylius by installing `league/uri:4.2.4` (to be tagged) which will use ` jeremykendall/php-domain-parser:4.0.4`. The perfect solution is to wait for Payum release all using new dependencies and the workaround is to properly tag its dependencies, all due to PHP 7.2 BC breaks, as our test suite is passing with current ones (just `-alpha` stability makes them really hard to install by a novice composer user).

**Comment by pamil** [comment]
Okay, 4.0.4 might be not needed, looks like we will get this worked out directly in Payum.
