### ISSUE TITLE
Host / Subdomain / Scheme *Question*

### ISSUE THREAD

**Issue by schulzefelix** [jeremykendall/php-domain-parser#212]
Hello,

first, great package thanks for that. I just have a few questions regarding the new version 5.

The URL parsing part is completely removed? So no chance to get the scheme, subdomain, host etc? Also I have to submit a host not an URL anymore?

Because in the earlier days I used it to parse something like https://www.example.com/en, but it seems like it don't like that anymore:

```
Domain {#703 ▼
  +"domain": "https://www.example.com/en"
  +"registrableDomain": "example.com/en"
  +"subDomain": "https://www"
  +"publicSuffix": "com/en"
  +"isKnown": false
  +"isICANN": false
  +"isPrivate": false
}
```

Thanks Felix

**Comment by nyamsprod** [comment]
@schulzefelix yes the URL parsing part has been removed because it had many issues and in the meantime better solution to correctly parse the URL exists in PHP.  Quoting the documentation

> PHP Domain Parser is built around accurate Public Suffix List based parsing. For URL parsing, building or manipulation please refer to [libraries](https://packagist.org/packages/sabre/uri?q=uri%20rfc3986&p=0) focused on those area of development.

**Comment by schulzefelix** [comment]
Ok cool, Thanks!
