### ISSUE TITLE
Internationalized domain name - IDN identification

### ISSUE THREAD

**Issue by adam741** [jeremykendall/php-domain-parser#228]
Hello,

Please, is the current version of the library provides a way to identify IDN or at least detect the IDN that have a non-English character like Chinese, Japanese & Arabic?

Thank you.

**Comment by nyamsprod** [comment]
@adam741 yes it does, that's why the library requires php `intl` extension to be used.

**Comment by adam741** [comment]
hmm, could you provide me an example for how to catch that please?

My code is:
```

<?php

use Pdp\Cache, Pdp\CurlHttpClient, Pdp\Manager;
$manager = new Manager(new Cache(), new CurlHttpClient());
$rules = $manager->getRules();

$parser = $rules->resolve("www.bébé.be");

?>
```

Just want the lib to tell me bébé.be is IDN

**Comment by adam741** [comment]
> 
> 
> @adam741 yes it does, that's why the library requires php `intl` extension to be used.

hmm, could you provide me an example for how to catch that please?

My code is:
```

<?php

use Pdp\Cache, Pdp\CurlHttpClient, Pdp\Manager;
$manager = new Manager(new Cache(), new CurlHttpClient());
$rules = $manager->getRules();

$parser = $rules->resolve("www.bébé.be");

?>
```

Just want the lib to tell me bébé.be is IDN

**Comment by nyamsprod** [comment]
@adam741 in the documentation you have two methods attached to the [DomainInterface](https://github.com/jeremykendall/php-domain-parser/blob/develop/src/DomainInterface.php#L70-L92) This should be enough to answer your question.
