### ISSUE TITLE
Don't swallow cache errors

### ISSUE THREAD

**Issue by AmazingDreams** [jeremykendall/php-domain-parser#232]
## Issue summary

I just spent an hour debugging an error about unable to load the domain information. Turned out the default cache implementation just swallows errors and fails with an irrelevant message.

### System informations

Irrelevant

## Standalone code, or other way to reproduce the problem

Make the default cache dir not writeable

### Expected result

Relevant error message

### Actual result

Irrelevant error message

**Comment by nyamsprod** [comment]
@AmazingDreams a bug fix has landed using the following PR #233 could you test it to see if it resolve your issue.

thanks in advance
