### ISSUE TITLE
ensure that publicSuffix not null in __debugInfo

### ISSUE THREAD

**Issue by Insolita** [jeremykendall/php-domain-parser#239]
## Issue summary
in method __debugInfo we get data from publicSuffix
https://github.com/jeremykendall/php-domain-parser/blob/develop/src/Domain.php#L225

But we get debug fails during debug "setLabels" method called from Domain constructor before than publicSuffix property have been initialized https://github.com/jeremykendall/php-domain-parser/blob/develop/src/Domain.php#L102
 
we should be fixed like
```php
    public function __debugInfo()
    {
        return [
            'domain' => $this->domain,
            'registrableDomain' => $this->registrableDomain,
            'subDomain' => $this->subDomain,
            'publicSuffix' =>$this->publicSuffix? $this->publicSuffix->getContent() : '',
            'isKnown' => $this->publicSuffix? $this->isKnown() : null, //or false
            'isICANN' => $this->publicSuffix? $this->isICANN() : null, //or false
            'isPrivate' => $this->publicSuffix? $this->isPrivate() : null, //or false
        ];
    }
```

**Comment by nyamsprod** [comment]
If I understand correctly `__debugInfo` is being called on an object on invalid state 🤔 . Since the object is on invalid state shouldn't it throw instead ? see https://3v4l.org/G6buQ

Seems exception can be thrown on `__debugInfo` and PHP does not complain 👍

**Comment by Insolita** [comment]
yes exception throwed. And it avoid catch real exception during debug (when we use xdebug with breakpoints and execute code step-by-step)

**Comment by Insolita** [comment]
it not sensitive during usual usage, but make problems during debug

**Comment by nyamsprod** [comment]
yes and TBH I think that for the next major release the `__debugInfo` method will be drop entirely. So  fixing it is really not top priority right now since what you are describing is a edge case.
