### ISSUE TITLE
Websites which use valid tlds for their domain don't seem to be treated correctly

### ISSUE THREAD

**Issue by Shardj** [jeremykendall/php-domain-parser#244]
"https://nhs.uk", "https://s3.amazonaws.com", "https://platform.sh"

I wasn't able to get the parts for domains such as the above, where the whole domain is a valid tld, but so is a subpart of the domain which in reality is the tld that the domain is using.

**Comment by nyamsprod** [comment]
@Shardj sorry but I don't understand your question. Could you provide a snippet so I can understand what your are asking ?

**Comment by Shardj** [comment]
Code:
```
        $manager = new Manager(new Cache(), new CurlHttpClient());
        $rules = $manager->getRules();
        $domain = $rules->resolve('platform.sh'); // any site using a tld for their domain
        var_dump($domain);
```
Output:
```
object(Pdp\Domain)[1314]
  public 'domain' => null
  public 'registrableDomain' => null
  public 'subDomain' => null
  public 'publicSuffix' => null
  public 'isKnown' => boolean false
  public 'isICANN' => boolean false
  public 'isPrivate' => boolean false
```

Try it with a normal url, for example 'www.google.co.uk' instead of one of the problematic urls that use a tld for their domain and you get regular results:

```
object(Pdp\Domain)[1315]
  public 'domain' => string 'www.google.co.uk' (length=16)
  public 'registrableDomain' => string 'google.co.uk' (length=12)
  public 'subDomain' => string 'www' (length=3)
  public 'publicSuffix' => string 'co.uk' (length=5)
  public 'isKnown' => boolean true
  public 'isICANN' => boolean true
  public 'isPrivate' => boolean false
```

**Comment by Shardj** [comment]
Worth noting that $manager->getTLDs() instead of $manager->getRules() seems to work fine, so maybe I'm just misunderstanding how this is supposed to work

**Comment by Shardj** [comment]
```new Domain('nhs.uk'); var_dump($domain); ``` also produces incorrect results

**Comment by nyamsprod** [comment]
@Shardj what your are reporting has already been addressed on [the pinned issue](https://github.com/jeremykendall/php-domain-parser/issues/240) which is the reason why it is pinned because it is a common mistake on how the package is used.

Please refer to that ticket for a full explanation and on how to get around it.

**Comment by Shardj** [comment]
Surely this is an issue to fix, a domain isn't invalid just because it encapsulates a tld for its domain

**Comment by nyamsprod** [comment]
There's a difference between:

```php
<?php

$domain = new Domain('platform.sh'); 
$domain = $manager->getRules()->resolve('platform.sh'); 
```
These two declarations are not meant to return the same thing.

The Domain resolver is not **just** a domain validator. It validates if the given domain is valid **AND** if its public suffix list is known/found/valid. In your example, the first assertion is true, not the second one so it returns `null`.

So IMHO this is not an issue you just need to understand the subtle difference between both calls.

**Comment by Shardj** [comment]
Sorry, please help me to understand why the public suffix list isn't known/found/valid for the example urls I've provided? For example nhs.uk the tld is uk.

**Comment by nyamsprod** [comment]
@Shardj just like explained in the documentation you are providing a public suffix **NOT** a valid domain name. A public suffix can not be resolved as explain on the public suffix website.

**Comment by Shardj** [comment]
Could you show me where it says that a public suffix cannot be a valid domain name and why not? After all, plenty of very valid websites do use domains which are a tld, so I'm just struggling to see what the reasoning is to say that they're invalid.

**Comment by nyamsprod** [comment]
@Shardj run this script locally on your server and you should understand what is happening. Again this is well documented so refer to the documentation if you do not understand the output else please refer to the algorithm as described in [PSL documentation website](https://publicsuffix.org/list/).

```php
<?php

use Pdp\Cache;
use Pdp\CurlHttpClient;
use Pdp\Manager;
use Pdp\Rules;

$manager = new Manager(new Cache(), new CurlHttpClient());
$rules = $manager->getRules();

var_dump(
    $rules->resolve('s3.amazonaws.com'),
    $rules->resolve('s3.amazonaws.com', Rules::ICANN_DOMAINS),
    $rules->resolve('s3.amazonaws.com', Rules::PRIVATE_DOMAINS),
    $rules->resolve('nhs.uk'),
    $rules->resolve('nhs.uk', Rules::ICANN_DOMAINS),
    $rules->resolve('nhs.uk', Rules::PRIVATE_DOMAINS)
);
```

**Comment by Shardj** [comment]
I know nyamsprod isn't interested in continuing with this issue, but for others reading this and for myself to refer back to.

Following the PSL documentation and using their algorithm which I've pasted below.

-     Match domain against all rules and take note of the matching ones.
-     If no rules match, the prevailing rule is "*".
-     If more than one rule matches, the prevailing rule is the one which is an exception rule.
-     If there is no matching exception rule, the prevailing rule is the one with the most labels.
-     If the prevailing rule is a exception rule, modify it by removing the leftmost label.
-     The public suffix is the set of labels from the domain which match the labels of the prevailing rule, using the matching algorithm above.
-     The registered or registrable domain is the public suffix plus one additional label.

The example of s3.amazonaws.com is considered valid by this repo only when checking the ICANN domains section of the psl list. Despite the psl agorithum also being able to come to the same conclusion when using all sections of the psl list, this repo doesn't come to that same conclusion.

The example of nhs.uk is considered valid by this repo only when using the private domains section of the psl list. Despite the psl algorithm also being able to come to the same conclusion when using all sections of the psl list, this repo doesn't come to that same conclusion.

I'll be going through the code to try and figure out why the code fails when comparing against all sections of the psl and I'll probably make a PR or use a branch if it's rejected.

**Comment by nyamsprod** [comment]
> I know nyamsprod isn't interested in continuing with this issue, but for others reading this and for myself to refer back to.

Please do not put out words or thoughts about what I think and what I will do. I tried to be respectful in our exchange, I may disagree but please stay on the issue. This type of remarks are not welcomed. 

If you think this is an issue that needs to be resolve, create a PR and it will be reviewed as soon as it is presented.

**Comment by Shardj** [comment]
Sorry nyamsprod, I wasn't trying to speak for you. I was simply trying to indicate that I wasn't commenting and expecting a response from you.

**Comment by nyamsprod** [comment]
>  I was simply trying to indicate that I wasn't commenting and expecting a response from you.

Then you should have just say that. This is an open source project to which we dedicate some of our free time. You may disagree with choices made but as long as you stay respectful issues will be tackle and PR reviewed when we have time. Behaviour like this will not be tolerated. 

You asked for the issue to be unlocked and I listened. I expect the same level of respect out of any contributor. The ball is on your side. If you PR can convince me then this issue and its related PR will be re-opened until then please refrain for making anymore comment not related to this issue.
