### ISSUE TITLE
Issue with .no domains

### ISSUE THREAD

**Issue by bacheson** [jeremykendall/php-domain-parser#246]
## Issue summary

I'm sure i'm missing something here but I can't get valid .no domains to resolve. For example: "techweb.no‎" returns null from resolve when it is indeed a valid domain.

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| Pdp version | 5.5.0 | 
| PHP version | 7.3.5  | 
| OS Platform | Ubuntu Xenial | 

## Standalone code, or other way to reproduce the problem

$manager = new Manager(new Cache(), new CurlHttpClient());
echo $manager->getRules()->resolve('www.techweb.no')->getRegistrableDomain();

### Expected result
techweb.no

### Actual result
null

**Comment by nyamsprod** [comment]
I've just copy paste your code and it worked for me 🤔 . Are you sure your cache is up to date ?
```php
<?php

declare(strict_types=1);

use Pdp\Domain;
use Pdp\Manager;
use Pdp\CurlHttpClient;
use Pdp\Cache;

require 'vendor/autoload.php';

$manager = new Manager(new Cache(), new CurlHttpClient(), new DateInterval('P1D'));
$rules = $manager->getRules();
var_dump(
    json_encode($rules->resolve('www.techweb.no')),
    json_encode(new Domain('www.techweb.no'))
);
```

The last parameter in the `Pdp\Manager` constructor was added in v5.4 to improve PSR-16 support. if omitted the cache will expires depending on the default setting of the underlying cache implementation used.

**Comment by bacheson** [comment]
Sorry this turned out to be an encoding issue...re-encoding in utf8 fixed my problem...thank you @nyamsprod for such quick assistance...sorry to waste your time
