### ISSUE TITLE
Options if we can't use composer?

### ISSUE THREAD

**Issue by morrow95** [jeremykendall/php-domain-parser#247]
Are there any options for those of us who aren't able to use composer?  This is exactly what I have been looking for, but I am not able to use composer in this particular situation.

**Comment by cebe** [comment]
I would not recommend it, but the release page offers a zip file download: https://github.com/jeremykendall/php-domain-parser/releases

**Comment by nyamsprod** [comment]
@morrow95  as @cebe said... if you download the release directly from the page you'll be responsible for resolving all the dependencies and run the post-install scripts. So it is possible ? yes. Is it recommend ? no.
