### ISSUE TITLE
getRegistrableDomain returns hostname instead of domain

### ISSUE THREAD

**Issue by ack202** [jeremykendall/php-domain-parser#262]
## Issue summary

```
$manager = new Manager(new Cache(), new CurlHttpClient());
$rules = $manager->getRules();
$domain = $rules->resolve('ec2-52-79-190-177.ap-northeast-2.compute.amazonaws.com')->getRegistrableDomain();
```

Will output the following: 

> string(54) "ec2-52-79-190-177.ap-northeast-2.compute.amazonaws.com"

### Expected result

I would expect to see "amazonaws.com"

**Comment by nyamsprod** [comment]
@ack202 thanks for using the library as stated in the documentation and in this recently closer issue https://github.com/jeremykendall/php-domain-parser/issues/260 you should explicitly use the resolve second argument to get the expected response
