### ISSUE TITLE
resolve "blogspot.com" error

### ISSUE THREAD

**Issue by wealding** [jeremykendall/php-domain-parser#269]
## Issue summary
resolve "blogspot.com" error

### System informations

| Information | Description |
|--------------|---------|
| Pdp version | 5.6.0 installed by composer |
| PHP version | 7.2  |
| OS Platform | centos 7 |

## Standalone code, or other way to reproduce the problem

$domain = $rules->resolve('blogspot.com');
var_dump($domain);

### Expected result
 ["domain"]=>'blogspot.com'

### Actual result
object(Pdp\Domain)#35 (7) { ["domain"]=> NULL ["registrableDomain"]=> NULL ["subDomain"]=> NULL ["publicSuffix"]=> NULL ["isKnown"]=> bool(false) ["isICANN"]=> bool(false) ["isPrivate"]=> bool(false) }

**Comment by wealding** [comment]
and "amazonaws.com" does not work too, others fine, why?

**Comment by nyamsprod** [comment]
hello @wealding this is expected behaviour. Please read the documentation to understand why it is this way.

**Comment by nyamsprod** [comment]
@wealding to be more complete the next feature release will make it more easily to get what you are looking for by introducing a simpler public API see #263 .
