### ISSUE TITLE
Second Level Domain

### ISSUE THREAD

**Issue by paduanton** [jeremykendall/php-domain-parser#282]
|    Q        |   A
|------------ | ------
| Version     | ^5.6

### Question

Is there any function I can use to get only the [SLD](https://en.wikipedia.org/wiki/Second-level_domain) of a \Pdp\Domain object or something like that?

I tried to use de getLabel(2) and getLabel(1), but they do not really worked for me.

Example:

Given the domain paduanton.dev.br or www.paduanton.digital I need a function that returns only **paduanton**.
Here is a solution to handle this:

`
            $domain    = $this->domain->getRegistrableDomain(); 
`
`
            $publicSuffix = $this->domain->getPublicSuffix();
`
`
            $domainSLD = str_replace('.' . $publicSuffix, '', $domain);
`

That works just fine, but does not look so good. Is there something better I can do with the library?

**Comment by nyamsprod** [comment]
I would go with a simpler solution or at least a more readable one:

```php
<?php

function fetchSecondLevelDomain($inputDomain): ?string
{
    $domain = $rules->resolve($inputDomain);
    if (!$domain->isResolvable()) {
        return null;
    }

    $publicSuffixLabelsCount = count(PublicSuffix::createFromDomain($domain));

    return $domain->getLabel($publicSuffixLabelsCount);
}
```
But a more general solution will land on the future v6 version.
