### ISSUE TITLE
Some questions, confusions

### ISSUE THREAD

**Issue by umairkhan-dev** [jeremykendall/php-domain-parser#283]
First of all, please pardon my ignorance. I wanted to post this in [Rewrite the documentation #275](https://github.com/jeremykendall/php-domain-parser/issues/275) as comment but thought to create a new post / issue.

**Some suggestions.**

**1.** Kindly do briefly explain in documentation
 -  what functions / properties of objects do. E.g. Like `isResolvable()` and `isKnown()` (common between **Pdp\Domain** and **Pdp\PublicSuffix** Objects).
 -  and what their return or values means. E.g. What is meant by `isResolvable` or `isKnown` of **Pdp\Domain** if their value is  `true`.

**2.** If I search some domain with TLD that does not exists in PSL, the parser still parse the domain and even `publicSuffix` index / key is populated. Is there a way to tell the parser to throw exception or return a `null` **Pdp\Domain** if TLD is not part of PSL (both ICANN and PRIVATE) in given domain.

 - Code sample
```
$res = $rules->resolve('paki.appri');
print_r($res);
var_dump($res);
```
 - Result
```
// Pdp\Domain Object
// (
//     [domain] => paki.appri
//     [registrableDomain] => paki.appri
//     [subDomain] => 
//     [publicSuffix] => appri
//     [isKnown] => 
//     [isICANN] => 
//     [isPrivate] => 
// )
// /var/www/html/tests.php:10:
// object(Pdp\Domain)[104]
//   private 'domain' => string 'paki.appri' (length=10)
//   private 'labels' => 
//     array (size=2)
//       0 => string 'appri' (length=5)
//       1 => string 'paki' (length=4)
//   private 'publicSuffix' => 
//     object(Pdp\PublicSuffix)[109]
//       private 'publicSuffix' => string 'appri' (length=5)
//       private 'section' => string '' (length=0)
//       private 'labels' => 
//         array (size=1)
//           0 => string 'appri' (length=5)
//       private 'asciiIDNAOption' => int 0
//       private 'unicodeIDNAOption' => int 0
//       private 'isTransitionalDifferent' => boolean false
//   private 'registrableDomain' => string 'paki.appri' (length=10)
//   private 'subDomain' => null
//   private 'asciiIDNAOption' => int 0
//   private 'unicodeIDNAOption' => int 0
//   private 'isTransitionalDifferent' => boolean false
```

**3.** Please provide a single concise full example consisting of major parts of this parser. Like you insists upon setting some scenario to update PSL (or RZD) cache. Here is an example of my test usage.
```
require_once(__DIR__ . DIRECTORY_SEPARATOR . 'vendor/autoload.php');
try {
    $manager = new \Pdp\Manager(new \Pdp\Cache(), new \Pdp\CurlHttpClient(), new DateInterval('P1D')); // Using Manager to make, refresh, update cache. new DateInterval('P1D') defines that cache is updated daily day.
    $rules = $manager->getRules(); //  Rules are fetched from cache and cache files are updated if needed as per DateInterval provide in Manager object creation.
    $domain = $rules->resolve('www.abc.enfield.sch.uk'); // Resolve provided domain and returns Pdp\Domain object.
    print_r($domain);
    var_dump($domain);
    var_dump($domain->getPublicSuffix()); // Returns PublicSuffix part of provided domain as string.
    // $ps = \Pdp\PublicSuffix::createFromDomain($domain); // Make and return Pdp\PublicSuffix object in reference to Pdp\Domain object.
    $ps = $rules->getPublicSuffix($domain); // Make and return Pdp\PublicSuffix object in reference to Pdp\Domain object.
    print_r($ps);
    var_dump($ps);
} catch (Exception $e) {
    var_dump($e);
}
```

**Environment.**
1. Ubuntu 18.04.
2. LAMP with PHP 7.4
3. jeremykendall/php-domain-parser 5.7.0 through Composer

I hope that I am able to explain my points properly.

Also I have a question that is not related to this **Parser** but as you have more knowledge of PSL and TLDs. Is there a way I can check which TLD is available for public registration and which are not? E.g. A normal person can register a `.com` domain but not `.google` because `.google` does not allow public registration. Some kind of list like PSL defining which TLDs are available for public registration.

**Comment by umairkhan-dev** [comment]
Sorry @nyamsprod for late reply.
Yes, I have read the documentation. And I know about `isKnown`, `isICANN` and `isPrivate` both as methods and **Pdp\Domain** object's properties. However the explanation in documentation about `get(Private|ICANN|Cookie)Domain`, especially

> **WARNING: If the Domain can not be resolved an exception is thrown.**

 made me confused about their actual working i.e as mentioned above

> From what I understand `get(Private|ICANN|Cookie)Domain` should behave like
> 
> 1. With `getCookieDomain`: parses the domain as per PSL rules, regardless `appri` itself exists in PSL list, returns \Pdp\Domain object or throws error / exception.
> 2. With `getICANNDomain`: parses the domain as per PSL rules and checks `appri` itself exists in ICANN section of PSL list, returns \Pdp\Domain object or throws error / exception.
> 3. With `getPrivateDomain`: parses the domain as per PSL rules and checks `appri` itself exists in Private section of PSL list, returns \Pdp\Domain object or throws error / exception.
> If I consider
> 
>> `getCookieDomain` is what you mean by `getPSLDomain` I think.
> 
> the number `1` point may be
> 
> 1. With `getCookieDomain`: parses the domain as per PSL rules and checks `appri` itself exists in ICANN section or Private section of PSL list, returns **\Pdp\Domain** object or throws error / exception.

I am very much obliged and thankful that you explained it to me and considered some changes in documentation.

I also request not to close this issue until rewriting of documentation.

Please consider editing your last comment. There is typo in it. I'll remove this section after your edit.


> ```
> Domain::isKnown(); // tells this is a known PS
> Domain::isCANN(); // tells this is a ICANN PS
> Domain::isCANN(); // tells this is a Prviate PS
> ```

**Comment by nyamsprod** [comment]
@umairkhan-dev I can pinned the issue so it can easily be seen but if the explanations given are enough I'll close it after editing my last comment for the typo 😉 
Also keep in mind that since I've started working on v6 I may rewrite the documentation for v5 and v6. which should improve the whole thing. But I still need to figure out some thing prior to that as it may take much more time.

**Comment by umairkhan-dev** [comment]
@nyamsprod. Yes, the explanation was more than enough. Thank you very much.

As for closing this issue and timing of rewriting the documentation, its up to you. Please do as you see fit. 😄

**Comment by umairkhan-dev** [comment]
I had previously requested that there are typos in your [comment](https://github.com/jeremykendall/php-domain-parser/issues/283#issuecomment-678644070).
> ```
> Domain::isKnown(); // tells the domain's public suffix is a known PS
> Domain::isCANN(); // tells the domain's public suffix is a ICANN PS
> Domain::isCANN(); // tells the domain's public suffix is a Prviate PS
> ```

**Comment by nyamsprod** [comment]
@umairkhan-dev should be fixed ... thanks for the remainder 😉
