### ISSUE TITLE
Exclamation marks and asterisks issue

### ISSUE THREAD

**Issue by alex-bacart** [jeremykendall/php-domain-parser#312]
## Issue summary

Some suffixes in [public_suffix_list.dat](https://publicsuffix.org/list/public_suffix_list.dat) are prefixed with exclamation marks or asterisks and it's an issue.

#### Some examples:
- `!city.kawasaki.jp`
- `*.awdev.ca`

### System informations

| Information | Description |
|--------------|---------|
| Pdp version | 6.0.0 |
| PHP version | 8.0.2 |
| OS Platform | Ubuntu |

## Standalone code, or other way to reproduce the problem
```php
echo Rules::fromPath('/public_suffix_list.dat')->resolve('www.city.kawasaki.jp')->registrableDomain()->value();
echo Rules::fromPath('/public_suffix_list.dat')->resolve('www.awdev.ca')->registrableDomain()->value();
```
### Expected result
`www.city.kawasaki.jp`
`www.awdev.ca`
### Actual result
`null`
`null`

**Comment by nyamsprod** [comment]
@alex-bacart thanks for using the library. What you are referring to is the syntax of the public suffix list. Please refer to [its documentation to understand ](https://publicsuffix.org/list/) what that syntax means for resolving accurately the different part of a domain. 

The bug you are describing **is** the expected behaviour.

Hope I have responded correctly to you issue.

**Comment by alex-bacart** [comment]
Well, actually I don't share your opinion about an expected behavior. But let it be.

**Comment by nyamsprod** [comment]
> Well, actually I don't share your opinion about an expected behavior. But let it be.

Well it is not my opinion, it is the specification and [there is a public test suite](https://raw.githubusercontent.com/publicsuffix/list/master/tests/test_psl.txt) to confirm that behaviour.

**Comment by alex-bacart** [comment]
@nyamsprod I've tried to execute my code once again and it seems I was wrong. By bad, sorry. Closing the issue.
