### ISSUE TITLE
The host is invalid?

### ISSUE THREAD

**Issue by JaredCostall** [jeremykendall/php-domain-parser#319]
## Issue summary

Trying to get the domain and TLD from a string, such as `https://www.example.co.uk => example.co.uk`

### System informations

| Information | Description |
|--------------|---------|
| Pdp version |  6.1
| PHP version |  8
| OS Platform |  OSX

## Standalone code, or other way to reproduce the problem

```
$topLevelDomains = TopLevelDomains::fromPath('iana.txt');
$domain = Domain::fromIDNA2008('https://www.google.com');

$result = $topLevelDomains->resolve($domain);
echo $result->registrableDomain()->toString();
```

### Expected result
`google.com`

### Actual result

>Pdp\\SyntaxError
>The host `https://www.google.com` is invalid: it contains invalid characters.

**Comment by nyamsprod** [comment]
@JaredCostall thanks for using the library.

`https://www.google.com` is an URI which contains 

- a scheme component: `https` 
- a host component: `www.google.com`

If you provide an URI to the library public API it will always fail. You should first use a URI parser to extract the host component of your URI before submitting it to the package API.

Hope my explanation will help you or other facing the same issue.
