### ISSUE TITLE
Incorrect suffix extraction on public suffix

### ISSUE THREAD

**Issue by mehrdadep** [jeremykendall/php-domain-parser#332]
## Issue summary

Incorrect public suffix extraction. Referencing [this](https://publicsuffix.org/list/public_suffix_list.dat) list for public suffix we know that the `eu.org` is a suffix but the code below returns `org`. Is there something that I'm missing?

### System informations

| Information | Description |
|--------------|---------|
| Pdp version | 6.1.1 |
| PHP version | 8.1 |
| OS Platform | Linux 5.19.0-76051900-generic |

## Standalone code, or another way to reproduce the problem

```
use Pdp\Rules;
use Pdp\Domain;

// The link is downloaded to this relative path
$publicSuffixList = Rules::fromPath('public.dat');
$domain = Domain::fromIDNA2008('test.eu.org');

$result = $publicSuffixList->resolve($domain)->suffix()->toString();

// print "org"
```

### Expected result

- `eu.org`

### Actual result

- `org`

**Comment by nyamsprod** [comment]
@mehrdadep thanks for using the library.

I believe the package is behaving as expected. Aren't you making a mistake between the suffix and the registrable domain part ?

`eu.org` is the registrable domain (the part of the domain against which you need to register your domain. for instance you can buy `test.eu.org`. 

The suffix is something else. Please read the documentation of check for more information on the internet.

**Comment by mehrdadep** [comment]
Yes, you're right. I forget to check the beginning of private domains section

**Comment by mehrdadep** [comment]
Based on the behavior of some of the `node` packages like [psl](https://github.com/peerigon/parse-domain/issues/147) and [parse-domain](https://www.npmjs.com/package/parse-domain), either this package is not working as expected or those two.

**Comment by nyamsprod** [comment]
@mehrdadep I have no knowledge on those package so you should
- provide clear, simple and reproducible script 
- read the documentation of each package and see if they do provide the same functionality as this package
- and probably open issues on their repository because AFAIK the behavior of this package do follow the PSL rules.

**Comment by mehrdadep** [comment]
Hi there again, reopening this issue because right now the packages act differently from when I opened the issue. Running this now outputs `eu.org`

```
use Pdp\Rules;
use Pdp\Domain;

// The link is downloaded to this relative path
$publicSuffixList = Rules::fromPath('public.dat');
$domain = Domain::fromIDNA2008('test.eu.org');

$result = $publicSuffixList->resolve($domain)->suffix()->toString();

```

**Comment by nyamsprod** [comment]
@mehrdadep please refer to the package CHANGELOG. a patch version was released recently to fix an inconsistency into the private domain parsing.
