### ISSUE TITLE
Composer package doesn't have Rules and Domains class anymore

### ISSUE THREAD

**Issue by wadih** [jeremykendall/php-domain-parser#344]
Seems like the latest composer package is completely different from previous versions.

No Rules.php, no Domain.php, seems the entire interface isn't the same at all. 

Downloaded the code with

    composer require jeremykendall/php-domain-parser

No src folder inside

Using composer 2.4.4 latest

**Comment by nyamsprod** [comment]
@wadih are you sure about your settings 🤔 . I just tried on a new directory and all went OK.

**Comment by wadih** [comment]
Hmm interesting, running it on another machine works.

On the problem machine I get below. So it's downloading version 1.4.2. Would you happen to know why?

```
./composer.json has been created
Running composer update jeremykendall/php-domain-parser
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking jeremykendall/php-domain-parser (1.4.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing jeremykendall/php-domain-parser (1.4.2): Extracting archive
Generating autoload files
No security vulnerability advisories found

```

On the good one I have:

```
./composer.json has been created
Running composer update jeremykendall/php-domain-parser
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking jeremykendall/php-domain-parser (6.1.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing jeremykendall/php-domain-parser (6.1.2): Extracting archive
4 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!

```

**Comment by nyamsprod** [comment]
I'm glad you were able to find the root cause and that it has nothing to do with the package. Unfortunately I am not a composer experts so I will clause the issue as it is not related to the package and I hope you will fin an good explanation for the observed behaviour.

**Comment by wadih** [comment]
Looks like the problem resolved itself after I installed `php-intl`
