### ISSUE TITLE
Parsing domain with ip prefix will not work

### ISSUE THREAD

**Issue by joe820912boy** [jeremykendall/php-domain-parser#347]
I found that some domain with ip prefix that the parser wouldn't work on it.

Like '1.1.1.1.cloudflare-dns.com' , the public suffix and top level domains just return nothing.

Does the parser not support this format, or is there anything I didn't notice it?

**Comment by nyamsprod** [comment]
@joe820912boy a PR has landed with a fix to this issue you can check, review and download it to see if all is fixed see #348

**Comment by joe820912boy** [comment]
@nyamsprod thanks for fix bug for some special format domain

and it seems that this fix didn't release for the current version?

I run composer update it didn't update anything, 

or should I manually edit the code?

**Comment by joe820912boy** [comment]
Oh,

I forget put the branch alias after update

@nyamsprod it's work now!! 

Thanks!!

**Comment by joe820912boy** [comment]
I have solved the problem by re-install the dev version.

`composer require jeremykendall/php-domain-parser:develop-dev`

Thanks!!
