### ISSUE TITLE
License issue with /test_data/public_suffix_list.dat

### ISSUE THREAD

**Issue by sylfabre** [jeremykendall/php-domain-parser#355]
## Issue summary

This repository is published under the MIT license 👍 but this file contains a reference to the Mozilla Public License v2
https://github.com/jeremykendall/php-domain-parser/blob/develop/test_data/public_suffix_list.dat

Fossa reports that as a potential licensing issue due to this inconsistency

### Expected result

Both the package and https://github.com/jeremykendall/php-domain-parser/blob/develop/test_data/public_suffix_list.dat uses the same license (hopefully MIT 🤞)

**Comment by nyamsprod** [comment]
@sylfabre thanks for using this library.

You are referring to a test file which is not included when you download the package AFAIK when using composer and which is used as mention as a test file without any modification made on it to validate that the package works as intended. It's present is made to reduce I/O calls to the original files as recommended by Mozilla itself.

The package on itself is registered and included in the list of package known to use the PSL here https://publicsuffix.org/learn/ 

I am not sure how the presence of that test file violates any licensing and I believe modifying that file would indeed represent a violation of such License.

So if you could give me more context on your issue I would certainly take the time to resolve it if deemed necessary.

**Comment by sylfabre** [comment]
@nyamsprod Thank you for looking into it.

Your explanation makes sense: there are no licensing issues.

https://fossa.com/ was only reporting a potential issue
