### ISSUE TITLE
Php 8.4 release?

### ISSUE THREAD

**Issue by JayceFFT** [jeremykendall/php-domain-parser#358]
Hi,

do you consider to create a release for php 8.4 support?
Composer is downloading an old version.

Thanks

**Comment by nyamsprod** [comment]
@JayceFFT Hi thanks for using the package. May I ask which version did you get 🤔. AFAIK the latest version is PHP 8.1+ compatible. So I do not understand your question?

**Comment by nyamsprod** [comment]
Ok got it ... Will see what I can do it's just a fix release nothing new

**Comment by nyamsprod** [comment]
version 6.3.1 is released.
