### ISSUE TITLE
Urls with IP addresses 

### ISSUE THREAD

**Issue by derdanu** [jeremykendall/php-domain-parser#43]
Parsing an URL with a IP address is causing invalid results.

subdomain, registerableDomain and publicSuffic should be false.

vago@hp:/tmp/test$ ./vendor/bin/parse http://67.196.2.34/whois-archive/latest.php?page=2479
Array
(
    [scheme] => http
    [user] => 
    [pass] => 
    [host] => 67.196.2.34
    [subdomain] => 67.196
    [registerableDomain] => 2.34
    [publicSuffix] => 34
    [port] => 
    [path] => /whois-archive/latest.php
    [query] => page=2479
    [fragment] => 
)
Host: http://67.196.2.34/whois-archive/latest.php?page=2479
'34' IS NOT a valid public suffix.

**Comment by jeremykendall** [comment]
Nice catch! Just released 2.0.3 with this fix.
