### ISSUE TITLE
Spaces?

### ISSUE THREAD

**Issue by nojacko** [jeremykendall/php-domain-parser#45]
I don't know if this is a bug or a quirk of domains names but spaces in the domain part of a URL seem to be allowed.

```php
$url = 'http://www. some . random. com/path/file.html';
$pslManager = new Pdp\PublicSuffixListManager();
$parser = new Pdp\Parser($pslManager->getList());
$url = $parser->parseUrl($url);
echo $url->host->registerableDomain; 
```
This echos " random. com", with the spaces.

Any thoughts?

**Comment by jeremykendall** [comment]
That is *wild*. It's certainly not intentional. It has to be a side-effect of never considering that case, never testing for it, and thereby allowing a very strange bug through.

What made you think to try adding spaces?

**Comment by jeremykendall** [comment]
php-domain-parser makes use of `[parse_url]`(http://php.net/parse_url) which, believe it or not, accepts spaces in domain names. I wonder if there's a good reason for that that I don't know of, or if it falls under quirk or bug. Check this out:

```
$ php -a
Interactive shell

php > $url = "http://www. some . random. com/path/file.html";
php > var_dump(parse_url($url));
array(3) {
  ["scheme"]=>
  string(4) "http"
  ["host"]=>
  string(23) "www. some . random. com"
  ["path"]=>
  string(15) "/path/file.html"
}
```

**Comment by jeremykendall** [comment]
Since php-domain-parser is based in large part around `parse_url` (`pdp_parse_url` is simply a UTF-8 friendly version of `parse_url`), I'm not going to alter the behavior of `parse_url` any more than I already have. I've opened #48 to address documenting that behavior.
