### ISSUE TITLE
Add support for generic schemes

### ISSUE THREAD

**Issue by akamustang** [jeremykendall/php-domain-parser#46]
Not quite sure what the following code in Parser.php is for:
```
if (preg_match(self::SCHEME_PATTERN, $url) === 0) {
  $url = 'http://' . preg_replace('#^//#', '', $url, 1);
}
```

I presume it's trying to ensure that a scheme is provided, however I would have thought that pdp_parse_url() would have schemeless support, but I've not tested if this is true or not.

Unfortunately SCHEME_PATTERN only allows schemes to be 'http' 'https' 'ftp' and 'ftps'.

Any chance we could have generic scheme support, i.e.
```
const SCHEME_PATTERN = '#^\w+://#i';
```

Or alternatively if it's doing this for some other reason make SCHEME_PATTERN a variable settable by passing an additional parameter to __construct(), so people that need generic support have that option.

Or even better have true schemeless support where $parts->scheme would be empty if it was empty in the original url, rather than forcing it to 'http'.

**Comment by jeremykendall** [comment]
I'll look into that. Good catch.

**Comment by jeremykendall** [comment]
> I presume it's trying to ensure that a scheme is provided ...

That's correct. `pdp_parse_url` is based on PHP's [`parse_url`](http://php.net/parse_url), which returns bad data if the scheme (*without* leading forward slashes) is not provided:

```
$ php -r "var_dump(parse_url('www.graphstory.com'));"
array(1) {
  'path' =>
  string(18) "www.graphstory.com"
}
```

Which is the same behavior you see in this library (with a NOTICE as I have `error_reporting = -1` in my dev env) *if* you leave out the `preg_match` you mentioned:

```
$ ./bin/parse www.graphstory.com
PHP Notice:  Undefined index: host in /Users/jeremykendall/dev/jeremykendall/php-domain-parser/src/Pdp/Parser.php on line 79
PHP Stack trace:
PHP   1. {main}() /Users/jeremykendall/dev/jeremykendall/php-domain-parser/bin/parse:0
PHP   2. Pdp\Parser->parseUrl() /Users/jeremykendall/dev/jeremykendall/php-domain-parser/bin/parse:25

Notice: Undefined index: host in /Users/jeremykendall/dev/jeremykendall/php-domain-parser/src/Pdp/Parser.php on line 79

Call Stack:
    0.0002     239400   1. {main}() /Users/jeremykendall/dev/jeremykendall/php-domain-parser/bin/parse:0
    0.0096    2266832   2. Pdp\Parser->parseUrl() /Users/jeremykendall/dev/jeremykendall/php-domain-parser/bin/parse:25

Array
(
    [scheme] =>
    [user] =>
    [pass] =>
    [host] =>
    [subdomain] =>
    [registerableDomain] =>
    [publicSuffix] =>
    [port] =>
    [path] => www.graphstory.com
    [query] =>
    [fragment] =>
)
Host: www.graphstory.com
'' IS NOT a valid public suffix.
```

You can pass schemeless URLs (*with* leading forward slashes) to `parse_url`:

```
$ php -r "var_dump(parse_url('//www.graphstory.com'));"
array(1) {
  'host' =>
  string(18) "www.graphstory.com"
}
```

This library will parse those correctly as well:

```
$ ./bin/parse //www.graphstory.com
Array
(
    [scheme] =>
    [user] =>
    [pass] =>
    [host] => www.graphstory.com
    [subdomain] => www
    [registerableDomain] => graphstory.com
    [publicSuffix] => com
    [port] =>
    [path] =>
    [query] =>
    [fragment] =>
)
Host: www.graphstory.com
'com' IS a valid public suffix.
```

> Unfortunately SCHEME_PATTERN only allows schemes to be 'http' 'https' 'ftp' and 'ftps'.

Yeah, that's lame.

> Any chance we could have generic scheme support ...

Absolutely. I'll add that as soon as I can. No promises on an ETA though. I'm always *insanely* busy at the moment.

> Or even better have true schemeless support where $parts->scheme would be empty if it was empty in the original url, rather than forcing it to 'http'.

Considering the above examples, schemeless URLs *are* supported, with the caveat that they must include two leading forward slashes. 

I think the fix there would be to prepend `//` to a URL that doesn't have a scheme rather than prepending `http://`. I'll add that feature as well.

**Comment by akamustang** [comment]
Fantastic reply, thanks for the extensive explanations.

> Absolutely. I'll add that as soon as I can. No promises on an ETA though. I'm always insanely busy at the moment.

Great, it's nice to know I wasn't trying to operate wildly out of spec.

> I think the fix there would be to prepend // to a URL that doesn't have a scheme rather than prepending http://. I'll add that feature as well.

Sounds like the way to go.

**Comment by jeremykendall** [comment]
@akamustang Done! https://github.com/jeremykendall/php-domain-parser/releases/tag/3.0.0

**Comment by akamustang** [comment]
Looks great, I'll test it soon.
