### ISSUE TITLE
Version string

### ISSUE THREAD

**Issue by akamustang** [jeremykendall/php-domain-parser#47]
Any chance a version string could be included in a file somewhere so it's possible to parse for it.

**Comment by jeremykendall** [comment]
Do you mean the current release version? As in `2.0.0` and `2.0.3`? 

Out of curiosity, why would you want that added?

My concern with adding a version string is that I'd constantly forget to update the string. I could add the `version` key to `composer.json`, but the [documentation for the `version` key](https://getcomposer.org/doc/04-schema.md#version) reflects my thinking and concerns about adding that:

> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.
> ... snip ...
> Specifying the version yourself will most likely end up creating problems at some point due to human error.

I'm not necessarily opposed to adding a version string somewhere in the library, but I'm concerned enough about keeping it updated that I'm leaning against adding it. Any thoughts on how I might automate version numbering?

**Comment by akamustang** [comment]
Yes I mean `2.0.3` or similar.

The reason would be so I could add `php-domain-parser` as a dependency, in another project, then check that anyone using the project includes a compatible version.

More specifically I'm using it as a library extension to a Drupal module, where someone that uses a module is expected to source and install the library themselves.

If you're interested here are some related linked:
https://www.drupal.org/node/1342238
http://www.drupalcontrib.org/api/drupal/contributions!libraries!libraries.module/function/libraries_get_version/7

**Comment by jeremykendall** [comment]
> The reason would be so I could add php-domain-parser as a dependency, in another project, then check that anyone using the project includes a compatible version.

I'm not familiar with Drupal, but could you add php-domain-parser via Composer? Because if so, you could parse the `composer.lock` file to find the current version of the library. 

I just did a little Googling and found a library to integrate Composer and Drupal: https://www.drupal.org/project/composer. I have no idea about the quality of that project, but it looks like Composer integration is at least possible.

**Comment by jeremykendall** [comment]
@akamustang Any additional thoughts? Is composer a non-starter for Drupal modules?

**Comment by jeremykendall** [comment]
@akamustang Is this still an issue for you?

**Comment by jeremykendall** [comment]
@akamustang I'm going to close this. Please feel free to reopen if you need additional help or would like to discuss further.
