### ISSUE TITLE
If scheme is not provided an empty string is returned, all other parts return null.

### ISSUE THREAD

**Issue by akamustang** [jeremykendall/php-domain-parser#53]
This bug is caused because mb_strtolower() will always return a string.

Here is a possible fix:

**Url.php**
```
- $this->scheme   = mb_strtolower($scheme, 'UTF-8');
+ $this->scheme   = $scheme ? mb_strtolower($scheme, 'UTF-8') : NULL;
```

**Comment by jeremykendall** [comment]
Can you give me more detail? How can I recreate the issue?

**Comment by akamustang** [comment]
Sure.

```
$parts = $parser->parseUrl('google.com');
$parts->user;   // Is NULL :D
$parts->pass;   // Is NULL :D
$parts->scheme; // Is '' (an empty string) :'(
```

**Comment by jeremykendall** [comment]
Oh, oh. I totally misunderstood the issue. Thanks for clearing that up :smile:. I'll get it taken care of.

**Comment by jeremykendall** [comment]
Thanks for all your help and input. If there were such thing as PHP Domain Parser swag, I'd send you some :smile:

**Comment by jeremykendall** [comment]
Aaaaaand finally fixing this. Sorry about the ridiculous delay.

**Comment by akamustang** [comment]
Thanks

**Comment by jeremykendall** [comment]
You're welcome!
