### ISSUE TITLE
Clean-up exception message for invalid url

### ISSUE THREAD

**Issue by akamustang** [jeremykendall/php-domain-parser#54]
`Invalid url php-lt-5.4.7-hack://<some-invalid-string>` isn't a very nice exception message.

My suggestion would be to strip the `php-lt-5.4.7-hack://` and put the string in quotes.

e.g. `Invalid url "<some-invalid-string>"`

**Comment by jeremykendall** [comment]
You're right. Where are you getting that message? In what context? Can you give me enough info to recreate it?

**Comment by akamustang** [comment]
The context is when an invalid url is provided to the parser, to test I used an empty string and it spat out:
`Invalid url php-lt-5.4.7-hack://`

Whereas I'd have expected it to say:
`Invalid url ""`

**Comment by jeremykendall** [comment]
Aha! Perfect, and thank you. I'll clean that up ASAP.

**Comment by jeremykendall** [comment]
It's only ~10 months later, but I'm finally fixing this one. Thanks again for the report!
