### ISSUE TITLE
getPublicSuffix("blogspot.com") returns blogspot.com

### ISSUE THREAD

**Issue by hfrid** [jeremykendall/php-domain-parser#56]
```php
require_once 'vendor/autoload.php';
$pslManager = new Pdp\PublicSuffixListManager();
$parser = new Pdp\Parser($pslManager->getList());
$dom_suffix = $parser->getPublicSuffix("blogspot.com");
echo $dom_suffix;
```

The above returns: blogspot.com. Here are some more examples:

dyndns-remote.com
dyndns.info
isteingeek.de
nieruchomosci.pl
podzone.net
saratov.ru

**Comment by jeremykendall** [comment]
@hfrid I see you closed this not long after opening. What was the solution?

**Comment by hfrid** [comment]
Sorry about that, should have left a comment. All the examples I provided
turned out to be valid suffixes according to the publicsuffixlist :D Thanks
for your work on this, its well appriciated!

- Henrik

**Comment by jeremykendall** [comment]
Totally understand. I've been confused by some of the parsing results myself from time-to-time.

Also be sure to keep your list updated: https://github.com/jeremykendall/php-domain-parser#refreshing-the-public-suffix-list. Parsing and results can change, although big changes aren't very frequent.

**Comment by hfrid** [comment]
The installation instructions still refer to the old version of
php-domain-parse ("jeremykendall/php-domain-parser": "~2.0" in the
composer.json). I also seem to be getting so odd results.

If i run "./vendor/bin/parse pasienterfaringer.no/asdasd/articles.php" I
get the expected result:

Array
(
    [scheme] =>
    [user] =>
    [pass] =>
    [host] => pasienterfaringer.no
    [subdomain] =>
    [registerableDomain] => pasienterfaringer.no
    [publicSuffix] => no
    [port] =>
    [path] => /asdasd/articles.php
    [query] =>
    [fragment] =>
)
Host: pasienterfaringer.no/asdasd/articles.php
'no' IS a valid public suffix.


However the following code renders an odd result:

require_once 'vendor/autoload.php';
$domain_unparsed =  "pasienterfaringer.no/asdasd/articles.php";
$pslManager = new Pdp\PublicSuffixListManager();
$parser = new Pdp\Parser($pslManager->getList());
$domain_parsed = $parser->getRegisterableDomain($domain_unparsed);
echo $domain_parsed;

RESULT: no/asdasd/articles.php

Any idea why?
