### ISSUE TITLE
Add CURL error check to CurlHttpAdapter.php

### ISSUE THREAD

**Issue by StyleT** [jeremykendall/php-domain-parser#58]
Currently in `CurlHttpAdapter.php` there are no check that curl finished execution with error. It's very important, because as we know cURL couldn't throw exceptions. 
For me, this situation has led to empty `public-suffix-list.php` after `bin/update-psl` run on production because of outdated CA bundle on server.

**Comment by jeremykendall** [comment]
@oxigenka I haven't heard back so I'm going to close this issue (and the related PR). Please feel free to add to the discussion here and we can revisit your PR. Thanks!
