### ISSUE TITLE
Proper accessors in classes

### ISSUE THREAD

**Issue by Saeven** [jeremykendall/php-domain-parser#60]
you open to a PR to add proper get/set methods to the objects?  Unfortunately I can't write phpspec tests  for my app when your lib is used, the magic __get breaks phpspec.

I can write up a PR really quickly (+, using magic accessors is bad form)

Thanks.
Alex

**Comment by jeremykendall** [comment]
I'm always open to PRs, but I'm concerned about changing the public API of the library. What about adding `@method` annotations? https://github.com/phpspec/prophecy/issues/80#issuecomment-170626785

> using magic accessors is bad form

Agreed, in most cases. I'm sure I had a good reason for it at the time, but I can't recall what it was now :-)

If you're willing to write up the PR, I will take it under serious consideration, especially as accessors are better than magic methods.

For what it's worth, I prefer to use as few setters as I can get away with (only as many as are strictly needed).

**Comment by Saeven** [comment]
PR opened up https://github.com/jeremykendall/php-domain-parser/pull/61

Tests are passing on my local machine on both PHP7.0.2 and PHP 5.6.17.  Travis CI is claiming 4 errors or so.  Not sure what it could be.
