### ISSUE TITLE
Cache file update not atomic

### ISSUE THREAD

**Issue by mikegreiling** [jeremykendall/php-domain-parser#78]
I intend to include this library in an app which automatically refreshes the public suffix list at regular intervals, but I am worried that the `file_put_contents` method used within the library is not atomic, so in theory a page request could come in while the file is being altered which uses a partially-written list.

https://github.com/jeremykendall/php-domain-parser/blob/6c1a256/src/Pdp/PublicSuffixListManager.php#L206

Could this method be rewritten to use a temporary file followed by an atomic `@rename()` instead?  I could put together a PR if you would accept it.

**Comment by jeremykendall** [comment]
> I am worried that the file_put_contents method used within the library is not atomic ...

You're correct. It never crossed my mind, and that's an obvious shortcoming in the library.

> I could put together a PR ...

Awesome!

> ... if you would accept it.

I never _promise_ to accept a PR, but I do promise to give it a thorough review and either 1) merge or 2) ask for modifications. I _rarely_ reject PRs, for what that's worth.

I'd also like to consider using [`flock`](http://php.net/flock) seeing as how that would avoid the use of a temp file, with the caveat that I've never used it myself and obviously don't have experience with atomic writes :disappointed: 

Thanks so much!

**Comment by nyamsprod** [comment]
@mikegreiling a new stable version of PHP Domain Parser has been released and it nows uses [PSR-16](http://www.php-fig.org/psr/psr-16/) instead of caching to resolve this issue and allowing caching the data in numerous backend not only files.
